### ISSUE TITLE
Specifying 'jdk-reflection' in the Gradle build file fails with an exception

### ISSUE THREAD

**Issue by centic9** [policeman-tools/forbidden-apis#99]
It seems the tool tries to append the Java 1.8 version to the bundled reflection-signature-file, but the file is not duplicated per Java version and thus loading it fails.

The following ones seem to work, especially jdk-system-out seems to be already handled without Java-version appended.

    bundledSignatures = [ 'jdk-unsafe', 'jdk-deprecated', 'jdk-system-out', 'commons-io-unsafe-2.4' ]

Exception during Gradle build is:

    Caused by: org.gradle.api.resources.ResourceException: IO problem while reading files with API signatures.
        at de.thetaphi.forbiddenapis.gradle.CheckForbiddenApis.checkForbidden(CheckForbiddenApis.java:531)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:589)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:572)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 49 more
    Caused by: java.io.FileNotFoundException: Bundled signatures resource not found: jdk-reflection-1.8
        at de.thetaphi.forbiddenapis.Checker.parseBundledSignatures(Checker.java:402)
        at de.thetaphi.forbiddenapis.Checker.parseBundledSignatures(Checker.java:387)
        at de.thetaphi.forbiddenapis.gradle.CheckForbiddenApis.checkForbidden(CheckForbiddenApis.java:511)
        ... 57 more

**Comment by uschindler** [comment]
Hi,
you are using version 2.0? Because this version does not yet have the jdk-reflection signatures file. The error message is a bit confusing, because it first tries to load "jdk-" signatures without target version and if it does not find it, it tries to load with version number. The error message is printed at end, so it prints version number in message.

I am about to release 2.1 quite soon (it has many fixes), I just wanted to wait for Java 9 class file version updates, so 2.1 is able to read java 9 class files with new version number.

So I will close this issue, if you confirm that you were using 2.0.

**Comment by centic9** [comment]
Ah, shoot, you are right of course, I am on 2.0 and looked at master, so this one is invalid.
